version: "3.9"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-apache_blog
    ports:
      - "8080:80"           
    volumes:
      - .:/var/www/html 
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0
    container_name: mysql_blog
    environment:
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_DATABASE: blog_sds
      MYSQL_USER: root 
      MYSQL_PASSWORD: rootpass
    ports:
      - "3306:3306"         
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass || exit 1"] 
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s


  phpmyadmin: 
    image: phpmyadmin:latest
    container_name: phpmyadmin_blog
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8082:80"         


volumes:
  db_data: